
# Config file for readthedocs.io : see https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
   builder: html
   configuration: docs/conf.py

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  apt_packages:
    - libkrb5-dev
    - graphviz

python:
  install:
    - requirements: docs/requirements.txt
