version: 2.1
jobs:
  test:
    parallelism: 3
    machine:
      # New tag format : https://discuss.circleci.com/t/new-image-tag-convention-for-ubuntu-linux-android-and-windows-vms/43750
      image: ubuntu-2204:2022.04.2
    steps:
      - run:
          name: "Install required packages"
          command: |
            source /etc/os-release
            sudo apt-get update
            sudo DEBIAN_FRONTEND=noninteractive apt-get install --assume-yes libkrb5-dev software-properties-common podman docker skopeo
            sudo ln -s /usr/bin/true /usr/bin/brew
            #sudo sed -i -E 's/(unqualified-search-registries = [[])(.*)/\1"registry.fedoraproject.org", "registry.access.redhat.com", \2/g' /etc/containers/registries.conf
            echo "unqualified-search-registries = ['registry.fedoraproject.org', 'registry.access.redhat.com', 'registry.centos.org', 'docker.io']" | sudo tee -a /etc/containers/registries.conf > /dev/null
            echo 'export PATH=~/.local/bin:$PATH' >> $BASH_ENV
            echo 'export REGISTRY_AUTH_FILE=/tmp/auth.json' >> $BASH_ENV
            mkdir -p $HOME/.local/bin
            cd ~/.local/bin && curl -L https://github.com/openshift/source-to-image/releases/download/v1.1.13/source-to-image-v1.1.13-b54d75d3-linux-amd64.tar.gz | tar xvz
      - checkout
      - run:
          name: "Versions"
          command: |
            echo "Docker:"
            docker version
            docker info
            echo "Podman:"
            podman version
            podman info
      - run:
          name: "Install required Python versions/packages"
          command: |
            pyenv uninstall -f 2.7.18

            pyenv install -s 3.7.13
            pyenv install -s 3.10.3
            pyenv local 3.7.13 3.10.3
            pip install "tox<4.0.0"
      - run: git config --global user.email "ci@dummy.com" && git config --global user.name "John Doe"
      - run: |
         if [[ "${CIRCLE_NODE_INDEX}" == 1 ]]; then
             make test-py37
         fi
      - run: |
          if [[ "${CIRCLE_NODE_INDEX}" == 2 ]]; then
             make test-py310
          fi

  docs-build:
    machine:
      image: ubuntu-2004:202111-02
    steps:
      - run:
          name: "Install required packages"
          command: |
            sudo apt-get update
            sudo apt install -y graphviz libkrb5-dev
      - checkout
      - run:
          name: "Install required Python versions/packages"
          command: |
            pyenv uninstall -f 2.7.18
            pyenv install 3.10.0
            pyenv local 3.10.0
            pip install virtualenv
      - run:
          name: Install docs dependencies
          command: |
            cd docs
            mkdir -p ./venv
            virtualenv ./venv
            . venv/bin/activate
            pip install -r ../requirements.txt -r requirements.txt
      - run:
          name: Generate documentation
          command: |
            cd docs
            . venv/bin/activate
            make html
      - store_artifacts:
          path: docs/_build

workflows:
  version: 2
  build:
    jobs:
      - test
      - docs-build
