name: GH-Action Workflow

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop

jobs:
  build:
    # https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#jobsjob_idif
    if: github.repository == 'cekit/cekit' # && github.event_name == 'pull_request'
    name: CI Testing
    strategy:
      fail-fast: false
      matrix:
        python-version: [ '3.6', '3.7', '3.8', '3.9', '3.10', '3.11' ]
        os: [macos-latest, ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Setup cache
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Setup Linux
      if: startsWith(matrix.os,'ubuntu')
      run: |
        sudo apt-get update
        sudo apt-get -y install libkrb5-dev software-properties-common containerd runc podman docker.io skopeo
        # https://bugs.launchpad.net/ubuntu/+source/docker.io/+bug/1844894
        sudo systemctl unmask docker
        sudo systemctl start docker
        docker version
        docker info
        podman version
        podman info
        pip install tox
        git config --global user.email "ci@dummy.com" && git config --global user.name "John Doe"
        echo "$HOME/.local/bin" >> $GITHUB_PATH
        mkdir -p $HOME/.local/bin
        cd $HOME/.local/bin && curl -sL https://github.com/openshift/source-to-image/releases/download/v1.1.13/source-to-image-v1.1.13-b54d75d3-linux-amd64.tar.gz | tar xvz
        PV=${{ matrix.python-version }}
    - name: Setup MacOS
      if: startsWith(matrix.os,'macos')
      run: |
        pip install tox
        brew install podman
        podman machine init
        podman machine start
        podman info
    - name: Run tests
      run: |
        PV=${{ matrix.python-version }}
        echo "Running for Python version $PV ( ${PV/./} )"
        make test-py"${PV/./}"
#    - name: Setup tmate session (only on failure)
#      uses: mxschmitt/action-tmate@v3
#      if: ${{ failure() }}
